2025-06-20 08:33:48,452 - orion_utils - ERROR - Failed to send data to Orion: HTTPConnectionPool(host='localhost', port=1026): Max retries exceeded with url: /v2/entities/ModbusDevice:001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2eb098b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-20 08:33:48,452 - __main__ - ERROR - Error processing SERVER1.SLAVE1: HTTPConnectionPool(host='localhost', port=1026): Max retries exceeded with url: /v2/entities/ModbusDevice:001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2eb098b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-20 08:33:53,489 - orion_utils - ERROR - Failed to send data to Orion: HTTPConnectionPool(host='localhost', port=1026): Max retries exceeded with url: /v2/entities/ModbusDevice:001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2eb098f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-20 08:33:53,489 - __main__ - ERROR - Error processing SERVER1.SLAVE1: HTTPConnectionPool(host='localhost', port=1026): Max retries exceeded with url: /v2/entities/ModbusDevice:001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2eb098f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-20 08:33:58,562 - orion_utils - ERROR - Failed to send data to Orion: HTTPConnectionPool(host='localhost', port=1026): Max retries exceeded with url: /v2/entities/ModbusDevice:001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2eb09b8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-20 08:33:58,563 - __main__ - ERROR - Error processing SERVER1.SLAVE1: HTTPConnectionPool(host='localhost', port=1026): Max retries exceeded with url: /v2/entities/ModbusDevice:001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2eb09b8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-20 08:34:03,612 - orion_utils - ERROR - Failed to send data to Orion: HTTPConnectionPool(host='localhost', port=1026): Max retries exceeded with url: /v2/entities/ModbusDevice:001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2eb0a6750>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-20 08:34:03,612 - __main__ - ERROR - Error processing SERVER1.SLAVE1: HTTPConnectionPool(host='localhost', port=1026): Max retries exceeded with url: /v2/entities/ModbusDevice:001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2eb0a6750>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-20 08:34:08,663 - orion_utils - ERROR - Failed to send data to Orion: HTTPConnectionPool(host='localhost', port=1026): Max retries exceeded with url: /v2/entities/ModbusDevice:001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2eb0a6a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-20 08:34:08,663 - __main__ - ERROR - Error processing SERVER1.SLAVE1: HTTPConnectionPool(host='localhost', port=1026): Max retries exceeded with url: /v2/entities/ModbusDevice:001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2eb0a6a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
